services:

  mysql:
    image: mysql:latest
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - internal

  nginx:
    image: nginx:alpine
    build:
      context:  .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80" # Mapeia porta 80 para o Host
    networks:
      - internal

  php:
    image: php:fpm
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/phpfpm/custom-fpm.ini:/usr/local/etc/php/conf.d/custom-fpm.ini
      - ./docker/phpfpm/custom-mysqli.ini:/usr/local/etc/php/conf.d/custom-mysqli.ini
    networks:
      - internal

networks:
  internal:
    driver: bridge