services:

  mysql:
    image: mysql:latest
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - internal

  nginx:
    build:
      context:  .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./php:/var/www/html
    image: nginx:alpine
    ports:
      - "80:80" # Mapeia porta 80 para o Host
    networks:
      - internal

  php:
    image: php:fpm #fpm-alpine
    volumes:
      - ./php:/var/www/html
      - ./php/ini/php.ini:/usr/local/etc/php/php.ini
    networks:
      - internal

networks:
  internal:
    driver: bridge