services:

  mysql:
    image: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    #ports:
    #  - "3306:3306"
    networks:
      - internal

  nginx:
    build:
      context:  .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src:/var/www/html
    image: nginx:alpine
    ports:
      - "80:80" # Mapeia porta 80 para o Host
    networks:
      - internal

  php:
    image: php:fpm-alpine
    volumes:
      - ./php:/var/www/html
    networks:
      - internal

networks:
  internal:
    driver: bridge